### ISSUE TITLE
功能请求：自动修正递进关系

### ISSUE THREAD

**Issue by tyf2018** [yalvhe2009/obsidian-title-serial-number-plugin#1]
请问能考虑增加一个设置选项，或者增加功能，以实现如下预期结果吗？

![image](https://user-images.githubusercontent.com/56342788/163304572-a0b1af29-b92c-471c-9c8d-64da6809b627.png)

**Comment by yalvhe2009** [comment]
可以的, 晚些时候我实现一下~

**Comment by yalvhe2009** [comment]
@tyf2018 已经发布0.0.2版本, 请更新插件后使用. 看看是否满足你的需求.

**Comment by yalvhe2009** [comment]
@tyf2018 试用完麻烦在这里反馈一下, 谢谢~

**Comment by tyf2018** [comment]
更新好快！能用，赞。不过跟我预想的有一点点出入。

我的层级标题没有严格地按照从H1至H6的逐级使用，而是经常跳级，而且跳级具有随机性，比如有时候是从从一级标题到三级，有时候是从一级直接跳到四级、甚至直接跳到五级（不同的文章排版要求不一样），您更新的这种设置方法对于我而言，有点固定了，不能自动地识别和忽略哪些层级。

当然这一版的设置功能相比上一版，自由度已经高了不少👏

也许是我的使用场景有点吹毛求疵了🤣希望有表述清楚。

**Comment by yalvhe2009** [comment]
@tyf2018 你所说的经常从一个级别跳转到另一个级别这种情况, 目前只能是根据不同文章分别去设置里面设置一下了. 目前没有很好的办法可以实现完全"自动".

或者你也可以提供一个算法, 或者算法的思路?

**Comment by tyf2018** [comment]
> 或者你也可以提供一个算法, 或者算法的思路?

我不懂编程🤣，有心无力

**Comment by yalvhe2009** [comment]
上次要回复你, 临时有事忘记了. 我认为目前我还做不到智能化的, 自动识别H几进行编号. 如果自动识别, 会存在很多逻辑上不通的问题. 目前只能优化到这样的程度了. 如果后续有想法了. 可以新开issue, 本issue我会标记为关闭.
