### ISSUE TITLE
有这么个现象，不知道是哪方的问题

### ISSUE THREAD

**Issue by chenxin0397** [yalvhe2009/obsidian-title-serial-number-plugin#3]
https://github.com/phibr0/obsidian-commander/issues/9

**Comment by yalvhe2009** [comment]
你这是使用了另一个插件?

**Comment by chenxin0397** [comment]
> 

是的，我用了另一个插件，但调用的仍旧是其他插件的功能，但唯有这个加序号的插件功能总丢失

**Comment by yalvhe2009** [comment]
嗯嗯, 我的命令都是通过obsidian标准接口暴露出来的. 建议看看另一个插件是否有误
